-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.tokens.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/webdav_tokens (
  wdt_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wdt_user_id INTEGER NOT NULL, wdt_filename BLOB NOT NULL,
  wdt_token BLOB NOT NULL, wdt_valid SMALLINT NOT NULL,
  wdt_expire INTEGER NOT NULL
);
