-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.locks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/webdav_locks (
  wdl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wdl_owner BLOB NOT NULL, wdl_timeout INTEGER UNSIGNED DEFAULT NULL,
  wdl_created BLOB DEFAULT NULL, wdl_token BLOB NOT NULL,
  wdl_scope SMALLINT NOT NULL, wdl_depth SMALLINT NOT NULL,
  wdl_uri BLOB NOT NULL
);

CREATE INDEX wdl_token ON /*_*/webdav_locks (wdl_token);

CREATE INDEX wdl_uri ON /*_*/webdav_locks (wdl_uri);
