-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.locks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/webdav_locks (
  wdl_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wdl_owner VARBINARY(255) NOT NULL,
  wdl_timeout INT UNSIGNED DEFAULT NULL,
  wdl_created BINARY(14) DEFAULT NULL,
  wdl_token VARBINARY(100) NOT NULL,
  wdl_scope TINYINT NOT NULL,
  wdl_depth TINYINT NOT NULL,
  wdl_uri LONGBLOB NOT NULL,
  INDEX wdl_token (wdl_token),
  INDEX wdl_uri (
    wdl_uri(100)
  ),
  PRIMARY KEY(wdl_id)
) /*$wgDBTableOptions*/;
