-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.tokens.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/webdav_tokens (
  wdt_id INT AUTO_INCREMENT NOT NULL,
  wdt_user_id INT NOT NULL,
  wdt_filename VARBINARY(255) NOT NULL,
  wdt_token VARBINARY(255) NOT NULL,
  wdt_valid TINYINT NOT NULL,
  wdt_expire INT NOT NULL,
  PRIMARY KEY(wdt_id)
) /*$wgDBTableOptions*/;
