-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.locks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE webdav_locks (
  wdl_id SERIAL NOT NULL,
  wdl_owner TEXT NOT NULL,
  wdl_timeout INT DEFAULT NULL,
  wdl_created TIMESTAMPTZ DEFAULT NULL,
  wdl_token TEXT NOT NULL,
  wdl_scope SMALLINT NOT NULL,
  wdl_depth SMALLINT NOT NULL,
  wdl_uri TEXT NOT NULL,
  PRIMARY KEY(wdl_id)
);

CREATE INDEX wdl_token ON webdav_locks (wdl_token);

CREATE INDEX wdl_uri ON webdav_locks (wdl_uri);
