-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.static.tokens.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE webdav_static_tokens (
  wdst_id SERIAL NOT NULL,
  wdst_user_id INT NOT NULL,
  wdst_token TEXT NOT NULL,
  wdst_expire INT NOT NULL,
  PRIMARY KEY(wdst_id)
);
