-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.tokens.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE webdav_tokens (
  wdt_id SERIAL NOT NULL,
  wdt_user_id INT NOT NULL,
  wdt_filename TEXT NOT NULL,
  wdt_token TEXT NOT NULL,
  wdt_valid SMALLINT NOT NULL,
  wdt_expire INT NOT NULL,
  PRIMARY KEY(wdt_id)
);
