-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.user.static.tokens.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE webdav_user_static_tokens (
  wdust_user_id INT NOT NULL, wdust_token TEXT NOT NULL
);
